name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  macos:
    uses: rime/librime/.github/workflows/macos-build.yml@master
    with:
      repository: rime/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}
