on: [push, pull_request, workflow_dispatch]

jobs:
  checkout:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

  macos:
    needs: checkout
    uses: rime/librime/.github/workflows/macos-build.yml@master
    with:
      repository: rime/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}

  windows:
    needs: checkout
    uses: rime/librime/.github/workflows/windows-build.yml@master
    with:
      repository: rime/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}
